Algoritmo "Fahrenheit para Celsius"
// Disciplina   : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Fahrenheit para Celsius
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 21/03/2024
Var
grausF, conversao: real

Inicio
Escreva("Digite a temperatura em Fahrenheit: ")
Leia(grausF)

conversao <- (grausF - 32) / 1.8
Escreva("Em Celsius fica: ", conversao)

Fimalgoritmo