Algoritmo "Troca De Valores"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Troca o valor de duas variaveis
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 18/03/2024
Var
num1, num2, aux:inteiro

Inicio
Escreva("Digite o primeiro valor: ")
Leia(num1)
Escreva("Digite o segundo valor: ")
Leia(num2)
aux <- num1
num1 <- num2
num2 <- aux

Escreva("Os valores trocados são, respectivamente: ", num1, num2)

Fimalgoritmo