Algoritmo "Número positivo"
// Disciplina   : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Verifique se o número é positivo ou negativo
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 21/03/2024
Var
   num: inteiro

Inicio
   Escreva("Escreva um número: ")
   Leia(num)
   Se (num >= 0) entao
      Escreva("É positivo")
   Senao
      Escreva("É negativo")
   Fimse


Fimalgoritmo