Algoritmo "Exercícios1F"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Divisiveis por 4
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 06/04/2024
Var
   count: inteiro

Inicio
   para count de 1 ate 200 passo 1 faca
      Se count % 4 = 0 entao
         Escreval("O número", count, " é divisivel por 4.")
      FimSe
   FimPara

Fimalgoritmo