Algoritmo "Exercícios1C"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Soma dos números de 1 a 100
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 06/04/2024
Var
   count, somados: inteiro

Inicio
   para count de 1 ate 100 passo 1 faca
      somados <- somados + count
   FimPara

   Escreva("O Somatório dos números de 1 a 100: ", somados)

Fimalgoritmo