Algoritmo "ExercicioARepita"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 03/04/2024
Var
   contadora: inteiro

Inicio
   contadora <- 15
   Repita
      Escreval("O número", contadora, " ao quadrado é: ", contadora ^ 2)
      contadora <- contadora + 1
   Ate contadora > 200


Fimalgoritmo