Algoritmo "Maior que 10"
// Disciplina   : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Verifique se o número é maior que 10
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 21/03/2024
Var
   num: inteiro

Inicio
   Escreva("Escreva um número: ")
   Leia(num)
   Se (num > 10) entao
      Escreva("É maior que 10!")
   Senao
      Escreva("Não é menor que 10!")
   Fimse


Fimalgoritmo