Algoritmo "Exercício5D"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Impares de 0 a 20
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 05/04/2024
Var
   count: inteiro

Inicio

   Enquanto count <= 20 faca
      Se count % 2 = 1 entao
         Escreval(count, " é Impar")
      FimSe
      count<- count + 1
   FimEnquanto

Fimalgoritmo