Algoritmo "Exercício5B"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Soma dos cem primeiros números
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 05/04/2024
Var
   count, soma: inteiro

Inicio

   Enquanto count <= 100 faca
      soma <- soma + count
      count<- count + 1
   FimEnquanto
   
   Escreva("A soma de todos os cem primeiros números é: ", soma)

Fimalgoritmo