Algoritmo "Exercicio4K"
// Disciplina   : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Número menor que 3
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 05/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor (menor que 3): ")
   Leia(num)

   Se num > 3 entao
      Escreva("Número maior que 3!")
   Senao
      Escreva("Número é: ", num)
   FimSe

Fimalgoritmo