Algoritmo "Exercicio4I"
// Disciplina   : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Valor par ou impar
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 05/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(num)

   Se num % 2 = 0 entao
      Escreva("O valor é par")
   Senao
      Escreva("O valor é impar")
   FimSe

Fimalgoritmo