Algoritmo "Exercício4B"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Modulo de um número
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 04/04/2024
Var
   num: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(num)

   Se num < 0 entao
      Escreva("O módulo de",num," é: ", num * -1)
   Senao
      Escreva("O módulo de",num," é: ", num)
   FimSe



Fimalgoritmo