Algoritmo "Área do Quadrado"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Area e Perimetro de um Quadrado
// Autor(a)    : Gerson Lucas Silva Leite
// Data atual  : 18/03/2024
Var
// Seção de Declarações das variáveis 
lado:real

Inicio

Escreval("Area do Quadrado")
Escreva("Digite o valor de um Lado: ")
Leia(lado)
Escreval("A Área é: ", lado * lado)

Fimalgoritmo